import { App } from 'vue';
import Button from './button/index.vue';
import Cell from './cell/index.vue';

// import Avatar from './__VUE/avatar/index.vue';
// import Cell from './__VUE/cell/index.vue';
// import CellGroup from './__VUE/cellgroup/index.vue';
// import Icon from './__VUE/icon/index.vue';
// import Price from './__VUE/price/index.vue';
// import OverLay from './__VUE/overlay/index.vue';
// import Divider from './__VUE/divider/index.vue';
// import Layout from './__VUE/layout/index.vue';
// import Col from './__VUE/col/index.vue';
// import Row from './__VUE/row/index.vue';
// import ImagePreview from './__VUE/imagepreview/index';
// import Swipe from './__VUE/swipe/index.vue';
// import ActionSheet from './__VUE/actionsheet/index.vue';
// import BackTop from './__VUE/backtop/index.vue';
// import Collapse from './__VUE/collapse/index.vue';
// import CollapseItem from './__VUE/collapseitem/index.vue';
// import Drag from './__VUE/drag/index.vue';
// import Dialog from './__VUE/dialog/index';
// import InfiniteLoading from './__VUE/infiniteloading/index.vue';
// import Notify from './__VUE/notify/index';
// import Range from './__VUE/range/index.vue';
// import Video from './__VUE/video/index.vue';
// import Popup from './__VUE/popup/index.vue';
// import Steps from './__VUE/steps/index.vue';
// import Step from './__VUE/step/index.vue';
// import Swiper from './__VUE/swiper/index.vue';
// import SwiperItem from './__VUE/swiperitem/index.vue';
// import Switch from './__VUE/switch/index.vue';
// import Toast from './__VUE/toast/index';
// import Progress from './__VUE/progress/index.vue';
// import CircleProgress from './__VUE/circleprogress/index.vue';
// import NoticeBar from './__VUE/noticebar/index.vue';
// import SearchBar from './__VUE/searchbar/index.vue';
// import Navbar from './__VUE/navbar/index.vue';
// import FixedNav from './__VUE/fixednav/index.vue';
// import Menu from './__VUE/menu/index.vue';
// import MenuItem from './__VUE/menuitem/index.vue';
// import Tabbar from './__VUE/tabbar/index.vue';
// import TabbarItem from './__VUE/tabbaritem/index.vue';
// import Elevator from './__VUE/elevator/index.vue';
// import Pagination from './__VUE/pagination/index.vue';
// import Tabs from './__VUE/tabs/index.vue';
// import TabPane from './__VUE/tabpane/index.vue';
// import Grid from './__VUE/grid/index.vue';
// import GridItem from './__VUE/griditem/index.vue';
// import Calendar from './__VUE/calendar/index.vue';
// import Checkbox from './__VUE/checkbox/index.vue';
// import CheckboxGroup from './__VUE/checkboxgroup/index.vue';
// import DatePicker from './__VUE/datepicker/index.vue';
// import InputNumber from './__VUE/inputnumber/index.vue';
// import Input from './__VUE/input/index.vue';
// import Radio from './__VUE/radio/index.vue';
// import RadioGroup from './__VUE/radiogroup/index.vue';
// import Rate from './__VUE/rate/index.vue';
// import Picker from './__VUE/picker/index.vue';
// import ShortPassword from './__VUE/shortpassword/index.vue';
// import TextArea from './__VUE/textarea/index.vue';
// import Uploader from './__VUE/uploader/index.vue';
// import CountUp from './__VUE/countup/index.vue';
// import NumberKeyboard from './__VUE/numberkeyboard/index.vue';
// import CountDown from './__VUE/countdown/index.vue';
// import Badge from './__VUE/badge/index.vue';
// import Tag from './__VUE/tag/index.vue';
// import Popover from './__VUE/popover/index.vue';
// import Form from './__VUE/form/index.vue';
// import FormItem from './__VUE/formitem/index.vue';
// import Cascader from './__VUE/cascader/index.vue';
// import Address from './__VUE/address/index.vue';
// import Barrage from './__VUE/barrage/index.vue';
// import Signature from './__VUE/signature/index.vue';
// import TimeSelect from './__VUE/timeselect/index.vue';
// import TimePannel from './__VUE/timepannel/index.vue';
// import TimeDetail from './__VUE/timedetail/index.vue';
// import Sku from './__VUE/sku/index.vue';
// import Card from './__VUE/card/index.vue';
// import Table from './__VUE/table/index.vue';

function install(app: App) {
  const packages = [Button, Cell];
  packages.forEach((item: any) => {
    if (item.install) {
      app.use(item);
    } else if (item.name) {
      app.component(item.name, item);
    }
  });
}
import './button/index.scss';

// import './__VUE/avatar/index.scss';
import './cell/index.scss';
// import './__VUE/cellgroup/index.scss';
// import './__VUE/icon/index.scss';
// import './__VUE/price/index.scss';
// import './__VUE/overlay/index.scss';
// import './__VUE/divider/index.scss';
// import './__VUE/layout/index.scss';
// import './__VUE/col/index.scss';
// import './__VUE/row/index.scss';
// import './__VUE/imagepreview/index.scss';
// import './__VUE/swipe/index.scss';
// import './__VUE/actionsheet/index.scss';
// import './__VUE/backtop/index.scss';
// import './__VUE/collapse/index.scss';
// import './__VUE/collapseitem/index.scss';
// import './__VUE/drag/index.scss';
// import './__VUE/dialog/index.scss';
// import './__VUE/infiniteloading/index.scss';
// import './__VUE/notify/index.scss';
// import './__VUE/range/index.scss';
// import './__VUE/video/index.scss';
// import './__VUE/popup/index.scss';
// import './__VUE/steps/index.scss';
// import './__VUE/step/index.scss';
// import './__VUE/swiper/index.scss';
// import './__VUE/swiperitem/index.scss';
// import './__VUE/switch/index.scss';
// import './__VUE/toast/index.scss';
// import './__VUE/progress/index.scss';
// import './__VUE/circleprogress/index.scss';
// import './__VUE/noticebar/index.scss';
// import './__VUE/searchbar/index.scss';
// import './__VUE/navbar/index.scss';
// import './__VUE/fixednav/index.scss';
// import './__VUE/menu/index.scss';
// import './__VUE/menuitem/index.scss';
// import './__VUE/tabbar/index.scss';
// import './__VUE/tabbaritem/index.scss';
// import './__VUE/elevator/index.scss';
// import './__VUE/pagination/index.scss';
// import './__VUE/tabs/index.scss';
// import './__VUE/tabpane/index.scss';
// import './__VUE/grid/index.scss';
// import './__VUE/griditem/index.scss';
// import './__VUE/calendar/index.scss';
// import './__VUE/checkbox/index.scss';
// import './__VUE/checkboxgroup/index.scss';
// import './__VUE/datepicker/index.scss';
// import './__VUE/inputnumber/index.scss';
// import './__VUE/input/index.scss';
// import './__VUE/radio/index.scss';
// import './__VUE/radiogroup/index.scss';
// import './__VUE/rate/index.scss';
// import './__VUE/picker/index.scss';
// import './__VUE/shortpassword/index.scss';
// import './__VUE/textarea/index.scss';
// import './__VUE/uploader/index.scss';
// import './__VUE/countup/index.scss';
// import './__VUE/numberkeyboard/index.scss';
// import './__VUE/countdown/index.scss';
// import './__VUE/badge/index.scss';
// import './__VUE/tag/index.scss';
// import './__VUE/popover/index.scss';
// import './__VUE/form/index.scss';
// import './__VUE/formitem/index.scss';
// import './__VUE/cascader/index.scss';
// import './__VUE/address/index.scss';
// import './__VUE/barrage/index.scss';
// import './__VUE/signature/index.scss';
// import './__VUE/timeselect/index.scss';
// import './__VUE/timepannel/index.scss';
// import './__VUE/timedetail/index.scss';
// import './__VUE/sku/index.scss';
// import './__VUE/card/index.scss';
// import './__VUE/table/index.scss';

export { Button, Cell };
export default { install, version: '3.1.12' };